/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // id("io.github.goooler.shadow") version "8.1.7"
    id("com.gradleup.shadow") version "9.0.0-beta8"

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("com.github.kurbatov:firmata4j:2.3.8")
    implementation("org.slf4j:slf4j-log4j12:1.7.29")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks {
    jar {
        manifest {
            attributes["Main-Class"] = application.mainClass
        }

    }
}